language: python
cache: pip
python:
  - "3.4"
  - "3.5"
  - "3.6"
env:
  - DJANGO=1.11
  - DJANGO=2.0
  - DJANGO=2.1
matrix:
  exclude:
  - env: DJANGO=2.0
    python: "3.4"
  - env: DJANGO=2.1
    python: "3.4"
  include:
  - python: "3.4"
  - python: "3.5"
  - python: "3.6"
  - python: "3.7"
    dist: xenial
    sudo: required
install:
  - pip install codecov pipenv
  - pipenv install --dev --system --skip-lock
script: pipenv run pytest -vv --cov modeltranslation_xliff
after_success:
  - codecov
notifications:
  email: false
