sudo: required

services:
  - docker

# It is not really needed, other than for showing correct language tag in Travis CI build log.
language: python

env:
  - CMD="docker exec -t ubuntu-test bash -c "
  - D_LC="LC_ALL=C.UTF-8"
  - D_LANG="LANG=C.UTF-8"

before_install:
  - docker run -d --name ubuntu-test -v $(pwd):/travis -e $D_LC -e $D_LANG ubuntu:latest tail -f /dev/null
  - docker ps

install:
  - $CMD "apt update"
  - $CMD "apt install -y apt-utils"
  - $CMD "apt install -y build-essential python3-dev python3-pip"
  - $CMD "apt install -y software-properties-common"
  - $CMD "apt-add-repository -y ppa:deadsnakes/ppa"
  - $CMD "apt update"
  - $CMD "apt install -y python3.4-dev python3.5-dev python3.7-dev"
  - $CMD "pip3 install --upgrade pip"
  - $CMD "pip3 install setuptools pipenv"

script:
  - $CMD "cd /travis"
  - $CMD "pipenv install --dev --skip-lock"
  - $CMD "pipenv run tox"

notifications:
    email: false
