language: python
dist: xenial
sudo: required
cache: pip
python:
  - "3.5"
  - "3.6"
  - "3.7"
env:
  - DJANGO=1.11
  - DJANGO=2.0
  - DJANGO=2.1
matrix:
  exclude:
  - env: DJANGO=1.11
    python: "3.7"
install:
  - pip install codecov tox tox-travis
script: tox
after_success:
  - codecov
notifications:
  email: false
