sudo: required

services:
  - docker

# It is not really needed, other than for showing correct language tag in Travis CI build log.
language: python
python: "3.6"

env:
  - CMD="docker exec -t ubuntu-test bash -c"

before_install:
  - docker run -d --name ubuntu-test --env-file .env-docker -v $(pwd):/travis -w /travis ubuntu:latest tail -f /dev/null
  - docker ps

install:
  - $CMD "apt update"
  - $CMD "apt install -y apt-utils locales"
  - $CMD "locale-gen en_US.UTF-8"
  - $CMD "apt install -y build-essential software-properties-common"
  - $CMD "apt-add-repository -y ppa:deadsnakes/ppa"
  - $CMD "apt update"
  - $CMD "apt install -y python3-dev python3-pip python3.4-dev python3.5-dev python3.7-dev"
  - $CMD "pip3 install --upgrade pip"
  - $CMD "pip3 install setuptools pipenv"

script:
  - $CMD "pipenv install --dev --system --skip-lock"
  - $CMD "pipenv run tox"

notifications:
    email: false
