sudo: required

services:
  - docker

# It is not really needed, other than for showing correct language tag in Travis CI build log.
language: python

env:
  - CMD="docker exec -t ubuntu-test bash -c"

before_install:
  - echo "LC_ALL=en_US.UTF-8" > .env-file
  - echo "LANG=en_US.UTF-8" >> .env-file
  - echo "LANGUAGE=en_US.UTF-8" >> .env-file
  - echo "PIPENV_DEFAULT_PYTHON_VERSION=3.6"
  - docker run -d --name ubuntu-test --env-file .env-file -v $(pwd):/travis ubuntu:latest tail -f /dev/null
  - docker ps

install:
  - $CMD "apt update"
  - $CMD "apt install -y locales"
  - $CMD "locale-gen en_US.UTF-8"
  - $CMD "apt install -y apt-utils"
  - $CMD "apt install -y build-essential python3-dev python3-pip"
  - $CMD "apt install -y software-properties-common"
  - $CMD "apt-add-repository -y ppa:deadsnakes/ppa"
  - $CMD "apt update"
  - $CMD "apt install -y python3.4-dev python3.5-dev python3.7-dev"
  - $CMD "pip3 install --upgrade pip"
  - $CMD "pip3 install setuptools pipenv"

script:
  - $CMD "cd /travis &&
          pipenv install --dev --skip-lock &&
          pipenv run tox"

notifications:
    email: false
